import crypto from "crypto";
import { prisma } from "../../services/prisma";
import { recordAuditEvent } from "../../services/auditLog";
import { HttpError } from "../../utils/httpError";
import { resolveOrgBase } from "../auth/rbac.service";
import { createScriptAsset } from "./scriptAssetUpload";

/**
 * Firewall Rule Sets (Windows network-remediation, Zero Networks-style) —
 * port of main.py:5025-5486. RESTORE MODEL is deliberately NOT a full
 * firewall snapshot/restore: every rule is tagged with a Group unique to its
 * rule set (firewallGroupTag), layered ON TOP of whatever's already on the
 * device. "Restore" just deletes every rule in that Group — whatever was
 * already there underneath is automatically back in effect. DELIVERY reuses
 * the existing 'runScript' MDM action verbatim (see mdmActionExecutor.ts's
 * applyFirewallRuleSet/restoreFirewallRuleSet branches).
 */

export const FIREWALL_GROUP_PREFIX = "BPSOAR-FW";

export function firewallGroupTag(ruleSetId: string): string {
  return `${FIREWALL_GROUP_PREFIX}-${ruleSetId}`;
}

/** Escapes a value for safe interpolation inside a PowerShell double-quoted string. Port of `_ps_escape` (main.py:5086). */
function psEscape(s: string | null | undefined): string {
  return (s || "").replace(/`/g, "``").replace(/"/g, '`"');
}

export interface FirewallRulePayload {
  id?: string | null;
  name?: string;
  direction?: string; // 'inbound' | 'outbound'
  action?: string; // 'block' | 'allow'
  protocol?: string; // 'TCP' | 'UDP' | 'Any'
  localPorts?: string;
  remoteAddresses?: string;
  profile?: string;
  enabled?: boolean;
}

/** One New-NetFirewallRule invocation. Port of `_firewall_rule_to_powershell` (main.py:5093-5122). */
function firewallRuleToPowershell(rule: FirewallRulePayload, groupTag: string, idx: number): string {
  const direction = (rule.direction || "inbound").toLowerCase() === "inbound" ? "Inbound" : "Outbound";
  const action = (rule.action || "block").toLowerCase() === "block" ? "Block" : "Allow";
  const displayName = `${groupTag}-${idx}-${(rule.name || "rule").slice(0, 60)}`;
  const parts = [
    `New-NetFirewallRule -DisplayName "${psEscape(displayName)}"`,
    `-Group "${groupTag}"`,
    `-Direction ${direction}`,
    `-Action ${action}`,
    `-Enabled ${rule.enabled !== false ? "True" : "False"}`,
  ];
  const protocol = (rule.protocol || "Any").trim();
  if (protocol.toLowerCase() !== "any") {
    parts.push(`-Protocol ${protocol}`);
    const localPorts = (rule.localPorts || "").trim();
    if (localPorts && localPorts.toLowerCase() !== "any") parts.push(`-LocalPort ${localPorts}`);
  }
  const remote = (rule.remoteAddresses || "").trim();
  if (remote && remote.toLowerCase() !== "any") parts.push(`-RemoteAddress "${psEscape(remote)}"`);
  const profile = (rule.profile || "Any").trim();
  if (profile.toLowerCase() !== "any") parts.push(`-Profile ${profile}`);
  return `${parts.join(" ")} | Out-Null`;
}

const WINDOWS_FIREWALL_OS_DEFAULT_INBOUND = "Block";
const WINDOWS_FIREWALL_OS_DEFAULT_OUTBOUND = "Allow";

export interface FirewallRuleSetLike {
  id: string;
  name: string;
  ensureFirewallEnabled: boolean;
  defaultInboundAction: string;
  defaultOutboundAction: string;
  rules: FirewallRulePayload[];
}

/** Port of `_generate_firewall_apply_script` (main.py:5127-5191). */
export function generateFirewallApplyScript(ruleSet: FirewallRuleSetLike): string {
  const group = firewallGroupTag(ruleSet.id);
  const name = ruleSet.name || "Firewall Rule Set";
  const rules = ruleSet.rules || [];
  const lines: string[] = [
    `# Auto-generated by Applivery SOAR — Firewall Rule Set "${psEscape(name)}"`,
    `# Rule set id: ${ruleSet.id}`,
    "# Do not edit on-device — make changes in Workflows > Firewall Policies and re-apply.",
    '$ErrorActionPreference = "Stop"',
    `$Group = "${group}"`,
    "",
    "# Idempotent: clear any rules we previously created under this group before recreating",
    "# them, so re-applying (rule set edited, workflow re-run) never leaves duplicates or",
    "# stale rules behind.",
    "Get-NetFirewallRule -Group $Group -ErrorAction SilentlyContinue | Remove-NetFirewallRule -ErrorAction SilentlyContinue",
    "",
  ];

  const profileCmd = ["Set-NetFirewallProfile", "-All"];
  if (ruleSet.ensureFirewallEnabled) profileCmd.push("-Enabled True");
  const defaultIn = ruleSet.defaultInboundAction || "notConfigured";
  const defaultOut = ruleSet.defaultOutboundAction || "notConfigured";
  if (defaultIn !== "notConfigured") profileCmd.push(`-DefaultInboundAction ${defaultIn[0].toUpperCase()}${defaultIn.slice(1)}`);
  if (defaultOut !== "notConfigured") profileCmd.push(`-DefaultOutboundAction ${defaultOut[0].toUpperCase()}${defaultOut.slice(1)}`);
  if (profileCmd.length > 2) {
    if (ruleSet.ensureFirewallEnabled) {
      lines.push(
        "# No EDR present (per this rule set's own configuration) — verify Windows Firewall",
        "# itself is enabled, otherwise nothing below would actually be enforced.",
      );
    } else {
      lines.push(
        "# EDR present (per this rule set's own configuration) — Windows Firewall's enabled",
        "# state is left exactly as-is; only the default posture below (if configured) changes.",
      );
    }
    if (defaultIn !== "notConfigured" || defaultOut !== "notConfigured") {
      lines.push(
        '# Changing the profile\'s DEFAULT action (not a rule) is what makes a genuine "allow',
        "# only these exceptions\" posture possible: Windows Firewall always lets an explicit",
        "# Block rule beat an explicit Allow rule regardless of which was created when or by",
        '# whom, so a "block everything, then allow X" pair of RULES would never actually let',
        "# X through. Flipping the profile default instead means unmatched traffic is blocked/",
        "# allowed by default, and this rule set's own Allow/Block rules below are what carve",
        "# out the exceptions — which behave normally against a changed default.",
      );
    }
    lines.push(profileCmd.join(" "), "");
  }

  if (rules.length) {
    lines.push(
      "# Block rules always take precedence over Allow rules in Windows Firewall",
      "# regardless of creation order — containment (Block) rules below are reliable",
      "# even alongside pre-existing/EDR-managed rules; a narrow Allow rule is only",
      "# guaranteed to hold if nothing else is blocking that same traffic first.",
    );
  }
  rules.forEach((rule, idx) => lines.push(firewallRuleToPowershell(rule, group, idx)));
  lines.push("", `Write-Output "Applied firewall rule set '${psEscape(name)}' (${rules.length} rule(s), group=$Group)."`);
  return lines.join("\n");
}

/** Port of `_generate_firewall_restore_script` (main.py:5193-5224). */
export function generateFirewallRestoreScript(ruleSet: FirewallRuleSetLike): string {
  const group = firewallGroupTag(ruleSet.id);
  const name = ruleSet.name || "Firewall Rule Set";
  const lines: string[] = [
    `# Auto-generated by Applivery SOAR — restores a device from Firewall Rule Set "${psEscape(name)}"`,
    `# Removes every rule this rule set created (group=${group}). Whatever firewall state`,
    "# pre-existed underneath is automatically back in effect once these are gone — no",
    "# snapshot was ever taken or is needed.",
    '$ErrorActionPreference = "Stop"',
    `$Group = "${group}"`,
    "Get-NetFirewallRule -Group $Group -ErrorAction SilentlyContinue | Remove-NetFirewallRule -ErrorAction SilentlyContinue",
  ];
  const defaultIn = ruleSet.defaultInboundAction || "notConfigured";
  const defaultOut = ruleSet.defaultOutboundAction || "notConfigured";
  if (defaultIn !== "notConfigured" || defaultOut !== "notConfigured") {
    const restoreCmd = ["Set-NetFirewallProfile", "-All"];
    if (defaultIn !== "notConfigured") restoreCmd.push(`-DefaultInboundAction ${WINDOWS_FIREWALL_OS_DEFAULT_INBOUND}`);
    if (defaultOut !== "notConfigured") restoreCmd.push(`-DefaultOutboundAction ${WINDOWS_FIREWALL_OS_DEFAULT_OUTBOUND}`);
    lines.push("# Revert the profile default posture this rule set changed, back to Windows' own OS default.", restoreCmd.join(" "));
  }
  lines.push(`Write-Output "Restored device from firewall rule set '${psEscape(name)}' (removed group=$Group)."`);
  return lines.join("\n");
}

/**
 * Generates fresh Apply/Restore PowerShell, uploads each as a new Applivery
 * script Asset, and creates (first save) or updates in place (later saves)
 * the two Action Library entries pointing at them. Port of
 * `_provision_firewall_ruleset_library_entries` (main.py:5259-5314).
 */
async function provisionFirewallRulesetLibraryEntries(
  authorization: string,
  orgBase: string,
  workspaceSlug: string,
  ruleSet: FirewallRuleSetLike,
  existingApplyId: string | null | undefined,
  existingRestoreId: string | null | undefined,
): Promise<{ applyId: string | null; restoreId: string | null; error: string | null }> {
  const applyScript = generateFirewallApplyScript(ruleSet);
  const restoreScript = generateFirewallRestoreScript(ruleSet);
  const uploadBase = orgBase.replace("https://api.applivery.io", "https://upload.applivery.io");
  const name = ruleSet.name || "Firewall Rule Set";
  const managedNote = "Auto-generated and managed by the Firewall Policy Library — edit the rule set there, not this entry.";

  const applyResult = await createScriptAsset(authorization, uploadBase, `${name} — Apply (Firewall)`, managedNote, applyScript, "windows", null, true);
  if (applyResult.error || !applyResult.asset) return { applyId: null, restoreId: null, error: `Could not upload the Apply script to Applivery: ${applyResult.error}` };
  const restoreResult = await createScriptAsset(authorization, uploadBase, `${name} — Restore (Firewall)`, managedNote, restoreScript, "windows", null, true);
  if (restoreResult.error || !restoreResult.asset) return { applyId: null, restoreId: null, error: `Could not upload the Restore script to Applivery: ${restoreResult.error}` };

  async function upsert(existingId: string | null | undefined, asset: { id: string; name?: string }, label: string): Promise<string> {
    if (existingId) {
      const entry = await prisma.actionLibraryEntry.findFirst({ where: { workspaceSlug, id: existingId } });
      if (entry) {
        await prisma.actionLibraryEntry.update({ where: { id: entry.id }, data: { assetId: asset.id, assetName: asset.name } });
        return entry.id;
      }
    }
    const created = await prisma.actionLibraryEntry.create({
      data: {
        workspaceSlug, type: "script", name: `${name} — ${label} (Firewall)`, description: managedNote,
        platform: "windows", assetId: asset.id, assetName: asset.name, arguments: "", scope: "machine",
      },
    });
    return created.id;
  }

  const applyId = await upsert(existingApplyId, applyResult.asset, "Apply");
  const restoreId = await upsert(existingRestoreId, restoreResult.asset, "Restore");
  return { applyId, restoreId, error: null };
}

// Starter templates offered when creating a new rule set — pre-fill the
// builder form, nothing more. Port of `FIREWALL_RULESET_TEMPLATES` (main.py:5352-5388).
export const FIREWALL_RULESET_TEMPLATES = [
  {
    key: "isolate_device",
    name: "Isolate Device",
    description: "Blocks all inbound and outbound traffic by default. Uses the firewall profile's own default posture (not block-all rules) specifically so genuine allow-exceptions are possible — add an Allow rule below for any management/agent traffic that must still get through, and enable it once you've filled in the real address range.",
    ensureFirewallEnabled: true,
    defaultInboundAction: "block",
    defaultOutboundAction: "block",
    rules: [
      { name: "Allow management traffic (edit me)", direction: "inbound", action: "allow", protocol: "Any", localPorts: "Any", remoteAddresses: "REPLACE-WITH-YOUR-MANAGEMENT-CIDR", profile: "Any", enabled: false },
    ],
  },
  {
    key: "block_lateral_movement",
    name: "Block Lateral Movement (SMB/RDP/WinRM)",
    description: "Blocks inbound SMB, RDP, and WinRM from anything — stops worm-style spread without fully isolating the device. No default-posture change needed; these are plain Block rules, which always win over any pre-existing Allow.",
    ensureFirewallEnabled: true,
    defaultInboundAction: "notConfigured",
    defaultOutboundAction: "notConfigured",
    rules: [
      { name: "Block SMB inbound", direction: "inbound", action: "block", protocol: "TCP", localPorts: "445", remoteAddresses: "Any", profile: "Any", enabled: true },
      { name: "Block RDP inbound", direction: "inbound", action: "block", protocol: "TCP", localPorts: "3389", remoteAddresses: "Any", profile: "Any", enabled: true },
      { name: "Block WinRM inbound", direction: "inbound", action: "block", protocol: "TCP", localPorts: "5985-5986", remoteAddresses: "Any", profile: "Any", enabled: true },
    ],
  },
  {
    key: "block_outbound_ip_cidr",
    name: "Block Outbound to IP/CIDR",
    description: "Ad-hoc containment for a specific address — e.g. a C2 address from a threat intel hit. Edit the Remote Addresses field and enable the rule before applying.",
    ensureFirewallEnabled: true,
    defaultInboundAction: "notConfigured",
    defaultOutboundAction: "notConfigured",
    rules: [
      { name: "Block outbound to target (edit me)", direction: "outbound", action: "block", protocol: "Any", localPorts: "Any", remoteAddresses: "REPLACE-WITH-TARGET-IP-OR-CIDR", profile: "Any", enabled: false },
    ],
  },
];

export async function listFirewallRuleSets(workspaceSlug: string) {
  return prisma.firewallRuleSet.findMany({ where: { workspaceSlug }, orderBy: { createdAt: "asc" } });
}

export interface FirewallRuleSetPayload {
  name: string;
  description?: string | null;
  ensureFirewallEnabled?: boolean;
  defaultInboundAction?: string;
  defaultOutboundAction?: string;
  rules: FirewallRulePayload[];
}

export async function createFirewallRuleSet(authorization: string, workspaceSlug: string, payload: FirewallRuleSetPayload, actorEmail: string) {
  const id = crypto.randomUUID();
  const rules = (payload.rules ?? []).map((r) => ({ ...r, id: r.id || crypto.randomUUID() }));
  const headers = { Authorization: authorization };
  const orgBase = await resolveOrgBase(headers, workspaceSlug);

  const draft: FirewallRuleSetLike = {
    id, name: payload.name, ensureFirewallEnabled: payload.ensureFirewallEnabled ?? true,
    defaultInboundAction: payload.defaultInboundAction ?? "notConfigured", defaultOutboundAction: payload.defaultOutboundAction ?? "notConfigured",
    rules,
  };
  const { applyId, restoreId, error } = await provisionFirewallRulesetLibraryEntries(authorization, orgBase, workspaceSlug, draft, null, null);
  if (error) throw new HttpError(502, error);

  const created = await prisma.firewallRuleSet.create({
    data: {
      id, workspaceSlug, name: payload.name, description: payload.description ?? "",
      ensureFirewallEnabled: draft.ensureFirewallEnabled, defaultInboundAction: draft.defaultInboundAction, defaultOutboundAction: draft.defaultOutboundAction,
      rules: rules as any, applyLibraryId: applyId, restoreLibraryId: restoreId,
    },
  });
  await recordAuditEvent(workspaceSlug, {
    category: "workflow", action: "firewall_ruleset_created", actor: actorEmail,
    targetType: "firewall_ruleset", targetId: created.id, targetName: created.name,
    message: `Firewall Rule Set "${created.name}" created (${rules.length} rule(s), ${draft.ensureFirewallEnabled ? "no EDR — will ensure firewall enabled" : "EDR present — firewall state left alone"})`,
  });
  return created;
}

export async function updateFirewallRuleSet(authorization: string, workspaceSlug: string, ruleSetId: string, payload: FirewallRuleSetPayload, actorEmail: string) {
  const existing = await prisma.firewallRuleSet.findFirst({ where: { workspaceSlug, id: ruleSetId } });
  if (!existing) throw new HttpError(404, "Firewall Rule Set not found");

  const rules = (payload.rules ?? []).map((r) => ({ ...r, id: r.id || crypto.randomUUID() }));
  const headers = { Authorization: authorization };
  const orgBase = await resolveOrgBase(headers, workspaceSlug);

  const draft: FirewallRuleSetLike = {
    id: ruleSetId, name: payload.name, ensureFirewallEnabled: payload.ensureFirewallEnabled ?? true,
    defaultInboundAction: payload.defaultInboundAction ?? "notConfigured", defaultOutboundAction: payload.defaultOutboundAction ?? "notConfigured",
    rules,
  };
  const { applyId, restoreId, error } = await provisionFirewallRulesetLibraryEntries(authorization, orgBase, workspaceSlug, draft, existing.applyLibraryId, existing.restoreLibraryId);
  if (error) throw new HttpError(502, error);

  const updated = await prisma.firewallRuleSet.update({
    where: { id: ruleSetId },
    data: {
      name: payload.name, description: payload.description ?? "",
      ensureFirewallEnabled: draft.ensureFirewallEnabled, defaultInboundAction: draft.defaultInboundAction, defaultOutboundAction: draft.defaultOutboundAction,
      rules: rules as any, applyLibraryId: applyId, restoreLibraryId: restoreId,
    },
  });
  await recordAuditEvent(workspaceSlug, {
    category: "workflow", action: "firewall_ruleset_updated", actor: actorEmail,
    targetType: "firewall_ruleset", targetId: ruleSetId, targetName: updated.name,
    message: `Firewall Rule Set "${updated.name}" updated (${rules.length} rule(s)) — on-device scripts regenerated, already-applied devices need the workflow action re-run to pick up the change`,
  });
  return updated;
}

export async function deleteFirewallRuleSet(workspaceSlug: string, ruleSetId: string, actorEmail: string) {
  const existing = await prisma.firewallRuleSet.findFirst({ where: { workspaceSlug, id: ruleSetId } });
  if (!existing) throw new HttpError(404, "Firewall Rule Set not found");
  await prisma.firewallRuleSet.delete({ where: { id: ruleSetId } });
  await recordAuditEvent(workspaceSlug, {
    category: "workflow", action: "firewall_ruleset_deleted", actor: actorEmail,
    targetType: "firewall_ruleset", targetId: ruleSetId, targetName: existing.name,
    message: `Firewall Rule Set "${existing.name}" deleted from the library. Devices it was already applied to keep those rules until explicitly restored.`,
  });
  return { status: "deleted" };
}
