<script setup lang="ts">
// Device Data Webhook tab. Port of main.py:7799-7897 (Settings side only —
// the actual receiver endpoints are TODO(Phase8), see
// deviceReportSecret.service.ts's module comment).
import { Alert, Button } from "@applivery/bluesky-vue";
import { onMounted, ref } from "vue";
import { useAuthStore } from "../../stores/auth";
import { useDeviceReportSecretStore } from "../../stores/deviceReportSecret";

const store = useDeviceReportSecretStore();
const auth = useAuthStore();
const busy = ref(false);
const downloading = ref<string | null>(null);

async function rotate() {
  busy.value = true;
  try { await store.rotate(); } finally { busy.value = false; }
}
async function clear() {
  busy.value = true;
  try { await store.clear(); } finally { busy.value = false; }
}
async function download(kind: "apps" | "security", platform: string) {
  downloading.value = `${kind}-${platform}`;
  try { await store.downloadScript(kind, platform, auth.orgSlug ?? "global"); } finally { downloading.value = null; }
}
function copyHeaders() {
  const secret = store.status?.secret ?? "";
  navigator.clipboard.writeText(`X-Workspace-Slug: ${auth.orgSlug}\nX-Device-Report-Secret: ${secret}`);
}

onMounted(async () => {
  await store.fetchStatus();
});
</script>

<template>
  <div class="space-y-6">
    <div>
      <h3 class="text-sm font-bold mb-2 text-gray-900">Device Data Webhook</h3>
      <p class="text-[11px] leading-relaxed text-gray-500 mb-3">
        Lets a scheduled script on a Windows or macOS device push extra attributes (disk encryption, firewall, patch status) that aren't in Applivery's own data, matched to a device by serial number.
      </p>
      <Alert v-if="store.error" type="danger">{{ store.error }}</Alert>

      <div class="p-5 rounded-xl border border-gray-200 bg-white space-y-3">
        <div v-if="store.status" class="flex items-center gap-2">
          <div class="w-2 h-2 rounded-full shrink-0" :class="store.status.configured ? 'bg-emerald-500' : 'bg-amber-500'" />
          <span class="text-xs font-semibold text-gray-900">
            <template v-if="store.status.configured">Webhook active for <span class="font-mono">{{ auth.orgSlug }}</span></template>
            <template v-else>Not configured for this workspace</template>
          </span>
        </div>

        <div v-if="store.status?.configured" class="space-y-2">
          <div>
            <label class="block text-[10px] font-medium mb-1 text-gray-500">Headers</label>
            <div class="flex items-start gap-1.5">
              <code class="flex-1 min-w-0 px-2.5 py-2 rounded-lg text-[11px] font-mono leading-relaxed whitespace-pre border border-gray-200 bg-gray-50">X-Workspace-Slug: {{ auth.orgSlug }}
X-Device-Report-Secret: {{ store.status.secret }}</code>
              <Button size="sm" variant="ghost" @click="copyHeaders">Copy</Button>
            </div>
          </div>
          <p class="text-[10px] text-gray-500" v-if="store.status.rotatedBy">Last generated by {{ store.status.rotatedBy }}.</p>
        </div>

        <div class="flex justify-end gap-2 pt-1">
          <Button v-if="store.status?.configured" variant="ghost" :loading="busy" @click="clear">Remove</Button>
          <Button variant="secondary" :loading="busy" @click="rotate">{{ store.status?.configured ? "Rotate secret" : "Generate webhook secret" }}</Button>
        </div>
      </div>
    </div>

    <div v-if="store.status?.configured">
      <h3 class="text-sm font-bold mb-2 text-gray-900">App Inventory Reporting</h3>
      <p class="text-[11px] leading-relaxed text-gray-500 mb-3">
        Reads each device's installed apps/versions locally and reports them into App List compliance and Vulnerability Service matching.
      </p>
      <div class="p-5 rounded-xl border border-gray-200 bg-white grid grid-cols-2 gap-2">
        <Button variant="ghost" :loading="downloading === 'apps-macos'" @click="download('apps', 'macos')">macOS script (.sh)</Button>
        <Button variant="ghost" :loading="downloading === 'apps-windows'" @click="download('apps', 'windows')">Windows script (.ps1)</Button>
      </div>
    </div>

    <div v-if="store.status?.configured">
      <h3 class="text-sm font-bold mb-2 text-gray-900">Security Attestation Reporting</h3>
      <p class="text-[11px] leading-relaxed text-gray-500 mb-3">
        Reports hardware/OS security posture (Secure Boot, BitLocker/FileVault, firewall, TPM) straight off the device, feeding the "Self-Reported Attribute" compliance condition.
      </p>
      <div class="p-5 rounded-xl border border-gray-200 bg-white grid grid-cols-2 gap-2">
        <Button variant="ghost" :loading="downloading === 'security-windows'" @click="download('security', 'windows')">Windows script (.ps1)</Button>
        <Button variant="ghost" :loading="downloading === 'security-macos'" @click="download('security', 'macos')">macOS script (.sh)</Button>
      </div>
    </div>
  </div>
</template>
