// Named-import registry for the Overview page's icon set. A wildcard
// `import * as SolarIcons from "@solar-icons/vue"` pulls the library's
// entire (huge) icon set into the bundle — it inflated the Overview chunk
// by ~11MB. Importing only the icons actually referenced (chrome buttons +
// every WIDGET_ICON_MAP / chart-type entry in analyticsCatalog.ts) keeps
// the bundle sane while still allowing dynamic `<component :is>` lookups
// by name (needed since the per-widget icon is picked at runtime from
// data, not known statically).
import {
  AddCircle,
  AddSquare,
  AltArrowDown,
  AltArrowLeft,
  AltArrowRight,
  AltArrowUp,
  ArrowRightUp,
  BatteryCharge,
  BatteryFull,
  Bell,
  Bolt,
  BookmarkSquare,
  Box,
  Bug,
  Buildings2,
  Calendar,
  Case,
  Chart2,
  ChartSquare,
  ChatRound,
  CheckCircle,
  Checklist,
  CloseCircle,
  ClockCircle,
  CloudDownload,
  CodeFile,
  Command,
  Cpu,
  DangerTriangle,
  Download,
  Eye,
  EyeClosed,
  Flag,
  Folder,
  Global,
  GraphUp,
  Hashtag,
  History,
  Hourglass,
  InfoCircle,
  Layers,
  Library,
  LinkCircle,
  List,
  Lock,
  LockUnlocked,
  Magnifer,
  MapPoint,
  MenuDots,
  MinusCircle,
  Pen,
  Pen2,
  PieChart,
  Play,
  PlugCircle,
  Pulse,
  Radar,
  Refresh,
  RefreshCircle,
  RestartCircle,
  Routing,
  Satellite,
  ShieldCheck,
  ShieldWarning,
  SliderHorizontal,
  Smartphone,
  SortVertical,
  Structure,
  Tag,
  Target,
  TestTube,
  TransferHorizontal,
  TrashBinMinimalistic,
  TrashBinTrash,
  UsersGroupRounded,
  Widget2,
} from "@solar-icons/vue";

export const ICONS = {
  AddCircle,
  AddSquare,
  AltArrowDown,
  AltArrowLeft,
  AltArrowRight,
  AltArrowUp,
  ArrowRightUp,
  BatteryCharge,
  BatteryFull,
  Bell,
  Bolt,
  BookmarkSquare,
  Box,
  Bug,
  Buildings2,
  Calendar,
  Case,
  Chart2,
  ChartSquare,
  ChatRound,
  CheckCircle,
  Checklist,
  CloseCircle,
  ClockCircle,
  CloudDownload,
  CodeFile,
  Command,
  Cpu,
  DangerTriangle,
  Download,
  Eye,
  EyeClosed,
  Flag,
  Folder,
  Global,
  GraphUp,
  Hashtag,
  History,
  Hourglass,
  InfoCircle,
  Layers,
  Library,
  LinkCircle,
  List,
  Lock,
  LockUnlocked,
  Magnifer,
  MapPoint,
  MenuDots,
  MinusCircle,
  Pen,
  Pen2,
  PieChart,
  Play,
  PlugCircle,
  Pulse,
  Radar,
  Refresh,
  RefreshCircle,
  RestartCircle,
  Routing,
  Satellite,
  ShieldCheck,
  ShieldWarning,
  SliderHorizontal,
  Smartphone,
  SortVertical,
  Structure,
  Tag,
  Target,
  TestTube,
  TransferHorizontal,
  TrashBinMinimalistic,
  TrashBinTrash,
  UsersGroupRounded,
  Widget2,
} as const;

export type IconName = keyof typeof ICONS;

export function resolveIcon(name: string) {
  return ICONS[name as IconName] ?? ICONS.ChartSquare;
}
