// Port of App.jsx's WIDGET_DESCRIPTIONS map (lines 1166-1226) — the
// "How is it calculated?" copy shown in WidgetInfoModal, keyed by
// widget.stat. Ported verbatim, all 62 entries.
export interface WidgetDescription {
  label: string;
  summary: string;
  desc: string;
}

export const WIDGET_DESCRIPTIONS: Record<string, WidgetDescription> = {
  stats_devices_os: { label: "Devices by OS", summary: "OS distribution", desc: "Shows the breakdown of enrolled devices across operating systems. Distribution helps plan platform-specific policies and resource allocation." },
  mdm_devices: { label: "Total Devices", summary: "Total devices", desc: "Total count of all enrolled devices in your MDM fleet. Tracks growth over time and gives a snapshot of your managed endpoint estate." },
  stats_devices_status: { label: "Device Status", summary: "Active devices", desc: "Tracks the operational state (Active, Inactive, Disabled) of all registered devices. Helps identify devices that may need attention or decommissioning." },
  stats_compliance: { label: "Compliance Status", summary: "Compliant devices", desc: "Measures how many devices meet your organisation's security policies. Non-compliant devices may be missing patches, configurations, or required apps." },
  stats_battery: { label: "Battery Levels", summary: "Battery health", desc: "Distribution of device battery levels across the fleet. Low battery devices may impact productivity; this metric helps plan charging station or battery replacement strategies." },
  stats_models: { label: "Device Models", summary: "Model distribution", desc: "Shows which hardware models are most common in your fleet. Useful for planning app compatibility, hardware refresh cycles, and support coverage." },
  stats_os_updates_all: { label: "OS Updates", summary: "Pending updates", desc: "Devices with available OS updates that have not yet been applied. Keeping OS versions current reduces security vulnerabilities across the fleet." },
  stats_os_versions: { label: "OS Versions", summary: "Version distribution", desc: "Breakdown of specific OS versions installed across your fleet. Version fragmentation can create compatibility and security risks." },
  stats_sync_errors: { label: "Sync Failures", summary: "Sync errors", desc: "Devices experiencing synchronisation failures with the MDM server. Persistent sync errors may indicate connectivity issues or misconfigured policies." },
  stats_devices_trend: { label: "Enrollment Trend", summary: "New enrollments", desc: "Shows device enrollment volume over the selected period. Enrollment spikes may correlate with onboarding campaigns or hardware refreshes." },
  mdm_users: { label: "Device Employees", summary: "Total users", desc: "Total MDM users with enrolled devices. Tracks headcount and helps align device-to-user ratios across departments." },
  mdm_collaborators: { label: "UEM Collaborators", summary: "Collaborators", desc: "Dashboard collaborators with access to UEM management features. Monitoring access helps maintain security and access governance." },
  mdm_segments: { label: "Segments", summary: "Segment count", desc: "Organisational segments used to scope device policies and visibility. Segments help manage large fleets by grouping devices by department, location, or function." },
  app_dist_apps: { label: "Enterprise Apps", summary: "Total apps", desc: "Enterprise apps distributed via the App Distribution platform. Tracks app portfolio size and platform coverage across iOS, Android, and Windows." },
  stats_builds_os: { label: "Builds by OS", summary: "Build distribution", desc: "Distribution of app build uploads by operating system. Helps understand where build activity is concentrated and plan testing resources." },
  stats_downloads_trend: { label: "Downloads Trend", summary: "Total downloads", desc: "App download volume over the selected period. Tracks adoption rates and helps identify periods of high distribution activity." },
  stats_builds_trend: { label: "Builds Trend", summary: "Total builds", desc: "App build upload volume over the selected period. Correlates with release cycles and development team activity." },
  app_dist_store_users: { label: "Store Users", summary: "Total employees", desc: "Employees with access to the App Store. Monitors store adoption and helps manage licence entitlements across the organisation." },
  app_dist_collaborators: { label: "Store Collaborators", summary: "Collaborators", desc: "Users with collaborator access to the App Distribution platform. Reviewing this list ensures access is appropriately scoped." },
  stats_collaborators: { label: "Collaborator Roles", summary: "Role distribution", desc: "Breakdown of collaborator access levels (Owner, Admin, Editor, Viewer). Helps enforce least-privilege access policies." },
  org_profile: { label: "Organisation", summary: "Profile", desc: "Your Applivery organisation profile including workspace name, plan details, and configuration status." },
  compliance_policies_summary: { label: "Compliance Policies", summary: "Total policies", desc: "Total Compliance Policies configured in this SOAR system, split by enabled vs. disabled. Tracks how much of your fleet is actively governed by automated compliance checks." },
  compliance_devices_violating: { label: "Devices in Violation", summary: "Devices out of compliance", desc: "Devices currently failing at least one Compliance Policy, right now, versus the rest of the fleet. Cleared automatically the moment a device recovers." },
  compliance_violations_by_policy: { label: "Violations by Policy", summary: "Active violations", desc: "Currently-violating devices broken down by which Compliance Policy they're failing. Highlights which policies are catching the most non-compliance." },
  compliance_violations_trend: { label: "Violations Trend", summary: "Violations detected", desc: "Volume of new Compliance Policy violations detected over the selected period. Spikes can flag a rollout gone wrong, a policy that's too strict, or a real fleet-wide drift." },
  compliance_review_queue: { label: "Review Queue Status", summary: "Queue breakdown", desc: "Current violations broken down by handling status — auto-fired, pending manual review, or lacking a linked workflow. Helps size the manual review workload." },
  autorun_safety_summary: { label: "autoRun Safety", summary: "Safety interventions", desc: 'How much of autoRun\'s recent activity was a normal auto-fire versus the blast-radius cap or circuit breaker stepping in. A rising "Blocked"/"Capped" share is worth investigating — it usually means a policy or its linked workflow needs attention.' },
  compliance_framework_coverage: { label: "Compliance Framework Coverage", summary: "Avg. coverage across frameworks", desc: "For each of ISO 27001, ENS, and NIS2: what share of that framework's device-level controls (from Compliance Policy Templates) currently has an enabled policy enforcing it in this workspace. A control with no matching policy counts as 0% covered — this is meant to surface gaps, not just celebrate progress." },
  iso27001_compliance_status: { label: "ISO 27001 Compliance Status", summary: "Devices violating an ISO 27001 control", desc: "Every ISO/IEC 27001:2022 control this app has a template for (Annex A.8.1 endpoint controls, A.8.7 malware protection, A.8.24 cryptography), broken down by how many devices are currently violating it. Only counts policies created from an ISO 27001 template and still tagged to it — see Compliance > New from Template. Covers only the device-configuration slice of ISO 27001; certification also requires an ISMS with no device-policy equivalent." },
  ens_compliance_status: { label: "ENS Compliance Status (mp.eq)", summary: "Devices violating an ENS control", desc: "Every Esquema Nacional de Seguridad mp.eq (equipment protection) control this app has a template for — encryption, screen lock, incident-reporting timeliness — broken down by how many devices are currently violating it. Only counts policies created from an ENS template and still tagged to it. Some controls are only mandatory at categoría alta; confirm against your declared ENS category." },
  nis2_compliance_status: { label: "NIS2 Compliance Status (Art. 21)", summary: "Devices violating a NIS2 control", desc: "Every NIS2 Directive Article 21(2) cyber-hygiene control this app has a template for — device configuration, vulnerability handling, cryptography, asset visibility — broken down by how many devices are currently violating it. Only counts policies created from a NIS2 template and still tagged to it. Article 21 also covers organizational measures (supply-chain security, incident procedures, governance) with no device-policy equivalent." },
  cases_summary: { label: "Cases", summary: "Open cases", desc: "All Cases broken down by status. The scorecard counts only Open/Investigating — the ones still needing attention." },
  cases_by_severity: { label: "Open Cases by Severity", summary: "Open cases", desc: "Currently open Cases broken down by severity — Low through Critical. Shows where analyst attention is most needed right now." },
  cases_by_source: { label: "Cases by Source", summary: "Total cases", desc: "Every Case broken down by how it was opened — manually by an analyst, from a Compliance Policy violation, or from an Inbound Webhook Trigger. Shows which entry point is actually generating the workload." },
  cases_trend: { label: "Cases Opened Trend", summary: "Cases opened", desc: "Volume of new Cases opened over the selected period, across every source. Spikes can flag a bad policy rollout, a noisy integration, or a real incident." },
  cases_sla_summary: { label: "Case SLA Status", summary: "Cases breached", desc: "Every open Case bucketed by SLA state — on track, acknowledge overdue, or resolve overdue — against the per-severity thresholds configured under Settings > Case SLA. A case breached on both clocks counts under the more severe (resolve) bucket." },
  cases_mttr_trend: { label: "Case MTTR Trend", summary: "Avg hours to resolve", desc: "Average time (in hours) from a Case opening to closing, grouped by the day it closed. A rising trend is the earliest signal that response capacity is falling behind volume." },
  applivery_events_by_type: { label: "Applivery Events by Type", summary: "Events received", desc: "Breakdown of Applivery's own native webhook events (device enrolled, MDM user changed, builds, bug/feedback reports, certificate expiry, and anything new Applivery adds) by event type. Reflects the last 50 events received — the same rolling window Settings > Applivery Events shows." },
  applivery_events_trend: { label: "Applivery Events Trend", summary: "Events received", desc: "Daily volume of Applivery native webhook events received over the selected period. Reflects only the last 50 events received, so a very active workspace may not show the full period." },
  applivery_automation_outcomes: { label: "Applivery Automation Outcomes", summary: "Events received", desc: "What actually happened when each Applivery event arrived — logged only, opened a Case, fired a Workflow, or got blocked pending a destructive-action acknowledgment. The fastest way to see whether Applivery Event rules are configured the way you expect." },
  system_health_summary: { label: "System Health", summary: "Jobs needing attention", desc: "Every background job in this app (Compliance evaluation, ticketing sync, Case SLA monitoring, scheduled reports, and more) bucketed by Healthy / Overdue / Erroring. Global across every workspace — matches Settings > System Health exactly, since it reads the same heartbeat registry." },
  os_updates_catalog_summary: { label: "OS Update Catalog", summary: "Known updates", desc: "Every Windows security update in the MSRC-sourced catalog (Settings > OS Updates), bucketed by severity. Foundation-phase, Windows only — a version-gap signal, not yet a vulnerability score." },
  os_updates_device_status_summary: { label: "OS Update Device Status", summary: "Devices behind", desc: "Your Windows fleet bucketed by patch status against the OS Update Catalog: up to date, confirmed behind, or possibly behind (unconfirmed build match). Foundation-phase — not yet wired into Compliance Policies or risk scoring." },
  vuln_catalog_summary: { label: "Apple/Android Vulnerability Catalog", summary: "Known CVEs", desc: "Every Apple (iOS/iPadOS, macOS) and Android CVE in the ENISA EUVD-sourced catalog (Settings > Vulnerability Catalog), bucketed by severity. Foundation-phase — a version-gap signal, not yet wired into Compliance Policies or risk scoring." },
  vuln_device_status_summary: { label: "Apple/Android Vulnerability Device Status", summary: "Devices behind", desc: "Your Apple and Android fleet bucketed by CVE exposure against the Vulnerability Catalog: up to date, confirmed behind, or possibly behind (Android's coarser major-version-only comparison). Foundation-phase — not yet wired into Compliance Policies or risk scoring." },
  vuln_service_device_status_summary: { label: "Vulnerability Service Device Status", summary: "Devices with CVEs", desc: "Your fleet bucketed by CVE exposure against your org's Vulnerability Service integration (Settings > Vulnerability Service): known-exploited (CISA KEV), critical/high, medium/low only, or clean. Covers all 4 platforms and both OS + installed apps — independent of, and additive to, the EUVD-based Vulnerability Device Status above. Only shows devices actually checked; requires the integration to be enabled." },
  os_lifecycle_summary: { label: "OS Lifecycle Catalog", summary: "Version trains", desc: "Every tracked Windows, iOS/iPadOS, macOS, and Android version train (Settings > OS Lifecycle) bucketed by support status — Maintained, End of life, or Unknown. Sourced from endoflife.date." },
  os_lifecycle_device_status_summary: { label: "OS Lifecycle Device Status", summary: "Devices on EOL OS", desc: "Your whole fleet (all 4 platforms) bucketed by whether its OS version still receives security support: Supported, End of life, or Unknown. The one signal that catches a device with zero pending CVEs simply because it's never been checked, not because it's current." },
  apple_app_updates_summary: { label: "Apple App Updates", summary: "Apps with an update available", desc: "Pending app updates across your Apple/macOS fleet (Settings > App Updates), sourced from Applivery's own HasUpdateAvailable signal per app — Apple's App Store/VPP metadata, not a version comparison we compute. Windows/Android aren't covered, since Applivery reports no equivalent field for them." },
  triggers_summary: { label: "Inbound Trigger Fires", summary: "Total fires", desc: "Every Inbound Webhook Trigger (the open-ended 3rd-party channel — EDR, MTD, DEX, SIEM, or anything else that can POST JSON to a URL) broken down by fire count. Lifetime counts per trigger, not limited to the selected date range." },
  triggers_fired_trend: { label: "Inbound Trigger Fires Trend", summary: "Fires", desc: "Daily volume of Inbound Webhook Trigger firings across every configured 3rd-party integration, from the Audit Log. A spike here usually means a specific EDR/MTD/DEX tool just got noisy — cross-check Settings > Inbound Webhooks." },
  workflow_runs_summary: { label: "Workflow Runs", summary: "Total runs", desc: "Every recorded Workflow run — manual, autoRun, Inbound Trigger, or Case Auto-Run Rule — broken down by outcome (completed, partial, failed) or still in progress." },
  workflow_runs_trend: { label: "Workflow Runs Trend", summary: "Runs started", desc: "Volume of Workflow runs started over the selected period, regardless of how they were triggered. Useful for spotting an automation that's firing far more (or less) than expected." },
  device_risk_distribution: { label: "Device Risk Distribution", summary: "Devices by risk tier", desc: "The live fleet broken down by risk tier (Low/Medium/High/Critical), computed from each device's security attestation, open Cases, and active violations. A point-in-time snapshot — see Device Risk Trend for how it moves over time." },
  device_risk_trend: { label: "Device Risk Trend", summary: "Avg. risk score", desc: 'The fleet\'s average risk score over time, read from the daily risk snapshot. Answers "is the fleet trending safer or riskier", which a single point-in-time view can\'t show.' },
  mitre_coverage: { label: "MITRE ATT&CK Coverage", summary: "Techniques covered", desc: "How many MITRE ATT&CK Enterprise techniques are mapped to at least one Compliance Policy or Case, out of the full catalog. A coverage gauge, not a detection-quality measure." },
  threat_intel_summary: { label: "Threat Intel Verdicts", summary: "IOCs checked", desc: "Every IOC lookup ever recorded on a Case, broken down by verdict (malicious/suspicious/clean/unknown), across manual and auto-enrichment checks alike." },
  ticketing_summary: { label: "Ticketing Sync", summary: "Linked tickets", desc: "Every Jira/ServiceNow ticket a Case has ever linked, and how many the inbound sync loop has confirmed are resolved on the ticket system's own side." },
};

/** Port of the original's inline fallback (App.jsx:1228). */
export function getWidgetInfo(stat: string | undefined, fallbackTitle: string | undefined): WidgetDescription {
  return WIDGET_DESCRIPTIONS[stat ?? ""] ?? { label: fallbackTitle ?? "", summary: "Total", desc: "Widget data from Applivery." };
}
